version: '3.5'
services:
  search_api:
    container_name: 'es_api'
    build: .
    restart: 'on-failure'
    ports:
      - '8080:8080'
    depends_on:
      - elasticsearch
    networks:
      - esapi_net
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_ADDR=:8080
      - CLIENT_CREDS=someid:somesecret
      - SIGN_KEY=certs/private.rsa
      - VERIFY_KEY=certs/public.rsa
      - TOKEN_EXPIRE_AT=3600

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200  
    networks:
      - esapi_net 
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    networks:
      - esapi_net      

networks:
  esapi_net:
    name: esapi_net   
