###

GET http://localhost:8080/v1/auth?creds=someid:somesecret

### 

GET http://localhost:8080/v1/products?q=sh
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY4Mjc3NzcsIlRva2VuVHlwZSI6InNlYXJjaF9hY2Nlc3MiLCJJbmZvIjp7IlNvdXJjZSI6InNlYXJjaGFwaSJ9fQ.zpMIPZ-l02LOfOw4ypMI9igcYJd0jjxlv2wVBUHb1rJxGIHfXtfeVouv8tVJtrTZmxeJLENkK9CYOQhUKkskQvmiIGcnLkeFpKJipX1agk-RgyoRPcDYVHD_Qfq8xhCRQ_wRGeKEMj71-HRAdKfyk7rjQ2wBRU8Nef6jo5ygKgtHf0vdkYd9FE42Nfnoklh2zSRIRRnN2CvEHHd-_9q2k5wr2_quISeogDZzftf8H49Ty0xkE6HDM_iiDWd6d6xPrcWK3DyGhVl-_gnOIU6J06cHQRlEVfan-X9PVOE7Oc28YYtgJq6h1WzYBDDNpLFlhjc9fJMKB5DpP1-_S8SNBw
###

GET http://localhost:8080/v1/products?q=summer&sort_by=brand&asc=false&limit=100&filter=brand:bkatrenko
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY4Mjc3NzcsIlRva2VuVHlwZSI6InNlYXJjaF9hY2Nlc3MiLCJJbmZvIjp7IlNvdXJjZSI6InNlYXJjaGFwaSJ9fQ.zpMIPZ-l02LOfOw4ypMI9igcYJd0jjxlv2wVBUHb1rJxGIHfXtfeVouv8tVJtrTZmxeJLENkK9CYOQhUKkskQvmiIGcnLkeFpKJipX1agk-RgyoRPcDYVHD_Qfq8xhCRQ_wRGeKEMj71-HRAdKfyk7rjQ2wBRU8Nef6jo5ygKgtHf0vdkYd9FE42Nfnoklh2zSRIRRnN2CvEHHd-_9q2k5wr2_quISeogDZzftf8H49Ty0xkE6HDM_iiDWd6d6xPrcWK3DyGhVl-_gnOIU6J06cHQRlEVfan-X9PVOE7Oc28YYtgJq6h1WzYBDDNpLFlhjc9fJMKB5DpP1-_S8SNBw

###

POST http://localhost:8080/v1/products
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY4Mjc3NzcsIlRva2VuVHlwZSI6InNlYXJjaF9hY2Nlc3MiLCJJbmZvIjp7IlNvdXJjZSI6InNlYXJjaGFwaSJ9fQ.zpMIPZ-l02LOfOw4ypMI9igcYJd0jjxlv2wVBUHb1rJxGIHfXtfeVouv8tVJtrTZmxeJLENkK9CYOQhUKkskQvmiIGcnLkeFpKJipX1agk-RgyoRPcDYVHD_Qfq8xhCRQ_wRGeKEMj71-HRAdKfyk7rjQ2wBRU8Nef6jo5ygKgtHf0vdkYd9FE42Nfnoklh2zSRIRRnN2CvEHHd-_9q2k5wr2_quISeogDZzftf8H49Ty0xkE6HDM_iiDWd6d6xPrcWK3DyGhVl-_gnOIU6J06cHQRlEVfan-X9PVOE7Oc28YYtgJq6h1WzYBDDNpLFlhjc9fJMKB5DpP1-_S8SNBw

[{
    "name": "ya",
    "brand": "fgfg",
    "key_words":["summer"]
}]